// <auto-generated />
using System;
using BussinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BussinessObject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231103114641_relationshipfix")]
    partial class relationshipfix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BussinessObject.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("BussinessObject.Content", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("blogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("userId", "blogId");

                    b.HasIndex("blogId");

                    b.ToTable("contents");
                });

            modelBuilder.Entity("BussinessObject.Meal", b =>
                {
                    b.Property<Guid>("menuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("foodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("menuId", "foodId");

                    b.HasIndex("foodId");

                    b.ToTable("meals");
                });

            modelBuilder.Entity("BussinessObject.Menu", b =>
                {
                    b.Property<Guid>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("categorysCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("menuDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menuPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menuPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menuType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MenuId");

                    b.HasIndex("categorysCategoryId");

                    b.ToTable("menus");
                });

            modelBuilder.Entity("BussinessObject.Order", b =>
                {
                    b.Property<Guid>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("orderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orderTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("paymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orderId");

                    b.HasIndex("paymentId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("BussinessObject.Schedule", b =>
                {
                    b.Property<Guid>("menuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("dateScheduled")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("menuId", "userId");

                    b.HasIndex("userId");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("BussinessObject.Service", b =>
                {
                    b.Property<Guid>("serviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("descriptionService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("serviceType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("serviceTypesServiceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("serviceId");

                    b.HasIndex("serviceTypesServiceTypeId");

                    b.ToTable("services");
                });

            modelBuilder.Entity("BussinessObject.ServiceType", b =>
                {
                    b.Property<Guid>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("nameServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("textServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("usersuserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceTypeId");

                    b.HasIndex("usersuserId");

                    b.ToTable("serviceTypes");
                });

            modelBuilder.Entity("BussinessObject.blog", b =>
                {
                    b.Property<Guid>("bolgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("blogContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blogName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blogPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("bolgId");

                    b.ToTable("blogs");
                });

            modelBuilder.Entity("BussinessObject.chatSection", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("messageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("userId", "messageId");

                    b.HasIndex("messageId");

                    b.ToTable("chatSection");
                });

            modelBuilder.Entity("BussinessObject.favoriteFood", b =>
                {
                    b.Property<Guid>("foodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("foodId", "userId");

                    b.HasIndex("userId");

                    b.ToTable("favoriteFoods");
                });

            modelBuilder.Entity("BussinessObject.feebackCategory", b =>
                {
                    b.Property<Guid>("feedbackCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("feedbackCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("feedbackCategoryId");

                    b.ToTable("feebackCategories");
                });

            modelBuilder.Entity("BussinessObject.feedback", b =>
                {
                    b.Property<Guid>("feedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("feebackCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("usersuserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("feedbackId");

                    b.HasIndex("feebackCategoryId");

                    b.HasIndex("usersuserId");

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("BussinessObject.food", b =>
                {
                    b.Property<Guid>("foodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("foodCalorios")
                        .HasColumnType("int");

                    b.Property<string>("foodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foodNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foodNutrition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foodPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foodProcessingVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foodTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("foodtimeProcess")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("foodId");

                    b.HasIndex("CategoryId");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("BussinessObject.ingredient", b =>
                {
                    b.Property<Guid>("ingredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("categorysCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ingredientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredientPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ingredientId");

                    b.HasIndex("categorysCategoryId");

                    b.ToTable("ingredients");
                });

            modelBuilder.Entity("BussinessObject.message", b =>
                {
                    b.Property<Guid>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("messageId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("BussinessObject.notification", b =>
                {
                    b.Property<Guid>("notificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notificationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("type")
                        .HasColumnType("int");

                    b.HasKey("notificationId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("BussinessObject.orderDetail", b =>
                {
                    b.Property<Guid>("orderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("serviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("unitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("orderId", "serviceId");

                    b.HasIndex("serviceId");

                    b.ToTable("orderDetails");
                });

            modelBuilder.Entity("BussinessObject.payment", b =>
                {
                    b.Property<Guid>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("orderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("paymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("paymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BussinessObject.paymentDetails", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("paymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("userId", "paymentId");

                    b.HasIndex("paymentId");

                    b.ToTable("paymentDetails");
                });

            modelBuilder.Entity("BussinessObject.recipe", b =>
                {
                    b.Property<Guid>("ingredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("foodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ingredientId", "foodId");

                    b.HasIndex("foodId");

                    b.ToTable("recipes");
                });

            modelBuilder.Entity("BussinessObject.role", b =>
                {
                    b.Property<Guid>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("roleId");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("BussinessObject.user", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("certificateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("notificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("rolesroleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("userId");

                    b.HasIndex("notificationId")
                        .IsUnique();

                    b.HasIndex("rolesroleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("BussinessObject.userBodyMax", b =>
                {
                    b.Property<Guid>("userInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BMIPerson")
                        .HasColumnType("real");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("createBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("heght")
                        .HasColumnType("int");

                    b.Property<int>("maximum_calories")
                        .HasColumnType("int");

                    b.Property<int>("minimum_calories")
                        .HasColumnType("int");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("users")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.HasKey("userInfoId");

                    b.HasIndex("users")
                        .IsUnique();

                    b.ToTable("userBodyMaxes");
                });

            modelBuilder.Entity("BussinessObject.Content", b =>
                {
                    b.HasOne("BussinessObject.blog", "blogs")
                        .WithMany("contents")
                        .HasForeignKey("blogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.user", "users")
                        .WithMany("contents")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("blogs");

                    b.Navigation("users");
                });

            modelBuilder.Entity("BussinessObject.Meal", b =>
                {
                    b.HasOne("BussinessObject.food", "foods")
                        .WithMany("meals")
                        .HasForeignKey("foodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Menu", "Menus")
                        .WithMany("meals")
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menus");

                    b.Navigation("foods");
                });

            modelBuilder.Entity("BussinessObject.Menu", b =>
                {
                    b.HasOne("BussinessObject.Category", "categorys")
                        .WithMany("menus")
                        .HasForeignKey("categorysCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("categorys");
                });

            modelBuilder.Entity("BussinessObject.Order", b =>
                {
                    b.HasOne("BussinessObject.payment", "payments")
                        .WithMany("orders")
                        .HasForeignKey("paymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("payments");
                });

            modelBuilder.Entity("BussinessObject.Schedule", b =>
                {
                    b.HasOne("BussinessObject.Menu", "menus")
                        .WithMany("schedules")
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.user", "users")
                        .WithMany("schedules")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("menus");

                    b.Navigation("users");
                });

            modelBuilder.Entity("BussinessObject.Service", b =>
                {
                    b.HasOne("BussinessObject.ServiceType", "serviceTypes")
                        .WithMany("services")
                        .HasForeignKey("serviceTypesServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("serviceTypes");
                });

            modelBuilder.Entity("BussinessObject.ServiceType", b =>
                {
                    b.HasOne("BussinessObject.user", "users")
                        .WithMany()
                        .HasForeignKey("usersuserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("BussinessObject.chatSection", b =>
                {
                    b.HasOne("BussinessObject.message", "messages")
                        .WithMany("chatSections")
                        .HasForeignKey("messageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.user", "users")
                        .WithMany("chatSections")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("messages");

                    b.Navigation("users");
                });

            modelBuilder.Entity("BussinessObject.favoriteFood", b =>
                {
                    b.HasOne("BussinessObject.food", "foods")
                        .WithMany("favoriteFoods")
                        .HasForeignKey("foodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.user", "users")
                        .WithMany("favoriteFoods")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("foods");

                    b.Navigation("users");
                });

            modelBuilder.Entity("BussinessObject.feedback", b =>
                {
                    b.HasOne("BussinessObject.feebackCategory", "feebackCategorys")
                        .WithMany("feedbacks")
                        .HasForeignKey("feebackCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.user", "users")
                        .WithMany("feedbacks")
                        .HasForeignKey("usersuserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("feebackCategorys");

                    b.Navigation("users");
                });

            modelBuilder.Entity("BussinessObject.food", b =>
                {
                    b.HasOne("BussinessObject.Category", null)
                        .WithMany("foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BussinessObject.ingredient", b =>
                {
                    b.HasOne("BussinessObject.Category", "categorys")
                        .WithMany("ingredients")
                        .HasForeignKey("categorysCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("categorys");
                });

            modelBuilder.Entity("BussinessObject.orderDetail", b =>
                {
                    b.HasOne("BussinessObject.Order", "orders")
                        .WithMany("orderDetails")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Service", "services")
                        .WithMany("orderDetails")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("orders");

                    b.Navigation("services");
                });

            modelBuilder.Entity("BussinessObject.paymentDetails", b =>
                {
                    b.HasOne("BussinessObject.payment", "payments")
                        .WithMany("paymentDetails")
                        .HasForeignKey("paymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.user", "users")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("payments");

                    b.Navigation("users");
                });

            modelBuilder.Entity("BussinessObject.recipe", b =>
                {
                    b.HasOne("BussinessObject.food", "foods")
                        .WithMany("recipes")
                        .HasForeignKey("foodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.ingredient", "ingredients")
                        .WithMany("recipes")
                        .HasForeignKey("ingredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("foods");

                    b.Navigation("ingredients");
                });

            modelBuilder.Entity("BussinessObject.user", b =>
                {
                    b.HasOne("BussinessObject.notification", "notifications")
                        .WithOne("users")
                        .HasForeignKey("BussinessObject.user", "notificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.role", "roles")
                        .WithMany("users")
                        .HasForeignKey("rolesroleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("notifications");

                    b.Navigation("roles");
                });

            modelBuilder.Entity("BussinessObject.userBodyMax", b =>
                {
                    b.HasOne("BussinessObject.user", "user")
                        .WithOne("userBodyMaxs")
                        .HasForeignKey("BussinessObject.userBodyMax", "users")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("BussinessObject.Category", b =>
                {
                    b.Navigation("foods");

                    b.Navigation("ingredients");

                    b.Navigation("menus");
                });

            modelBuilder.Entity("BussinessObject.Menu", b =>
                {
                    b.Navigation("meals");

                    b.Navigation("schedules");
                });

            modelBuilder.Entity("BussinessObject.Order", b =>
                {
                    b.Navigation("orderDetails");
                });

            modelBuilder.Entity("BussinessObject.Service", b =>
                {
                    b.Navigation("orderDetails");
                });

            modelBuilder.Entity("BussinessObject.ServiceType", b =>
                {
                    b.Navigation("services");
                });

            modelBuilder.Entity("BussinessObject.blog", b =>
                {
                    b.Navigation("contents");
                });

            modelBuilder.Entity("BussinessObject.feebackCategory", b =>
                {
                    b.Navigation("feedbacks");
                });

            modelBuilder.Entity("BussinessObject.food", b =>
                {
                    b.Navigation("favoriteFoods");

                    b.Navigation("meals");

                    b.Navigation("recipes");
                });

            modelBuilder.Entity("BussinessObject.ingredient", b =>
                {
                    b.Navigation("recipes");
                });

            modelBuilder.Entity("BussinessObject.message", b =>
                {
                    b.Navigation("chatSections");
                });

            modelBuilder.Entity("BussinessObject.notification", b =>
                {
                    b.Navigation("users")
                        .IsRequired();
                });

            modelBuilder.Entity("BussinessObject.payment", b =>
                {
                    b.Navigation("orders");

                    b.Navigation("paymentDetails");
                });

            modelBuilder.Entity("BussinessObject.role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("BussinessObject.user", b =>
                {
                    b.Navigation("chatSections");

                    b.Navigation("contents");

                    b.Navigation("favoriteFoods");

                    b.Navigation("feedbacks");

                    b.Navigation("schedules");

                    b.Navigation("userBodyMaxs")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
